#!/bin/sh


if [ $# -eq 0 ]
  then
	echo Use this tool to dump a postgres database to backup
	echo Usage: './backupPostgresForCopy <dbname>'
	exit;
fi

echo dumping database $1
pg_dump -h mars --no-owner --no-privileges -d $1 -p 22500 > /tmp/$1.dump

ls -las /tmp/$1.dump

echo Create new database, then run this file through psql.
