#!/bin/sh


if [ $# -eq 0 ]
  then
	echo Use this tool to dump a postgres database to backup
	echo Usage: './backupPostgresForCopy <dbname>'
	exit;
fi

echo dumping database $1
pg_dump -h mars --clean --no-owner --no-privileges --if-exists -d $1 -p 22500 > /tmp/$1.dump
