#!/bin/sh

if [ $# -eq 0 ]
  then
	echo Usage "$0 <dbname> <schema> <path to sqlite database"
	exit;
fi

DB=$1
SCHEMA=$2
SQLITEDB=$3
PORT=22500
HOST=mars
TEMPDB=tempdb

echo DB $DB
echo SCHEMA $SCHEMA
echo SQLITEDB $SQLITEDB

echo exporting database
OUTFILE=/tmp/$DB\_$SCHEMA

cat >$OUTFILE <<EOF
BEGIN;
PRAGMA foreign_keys=off;
DELETE FROM record WHERE record_id=0;
EOF

pg_dump --dbname=$DB --host=$HOST --port=$PORT \
	--no-owner \
	--no-privileges \
	--column-inserts \
	--inserts \
	--no-security-labels \
	--section=data \
	-T article                     \
	-T config_daemon               \
	-T config_host                 \
	-T config_host_digital_format  \
	-T configuration               \
	-T digital_format              \
	-T greatest_hits_record        \
	-T namespace                   \
	-T password                    \
	-T source                      \
	-T status                      \
	-T public.password_userid_seq  \
	-T search_result               \
	-T $SCHEMA.category            \
	-T $SCHEMA.category_index      \
	-T genre                       \
	-t $SCHEMA.artist              \
	-t $SCHEMA.artist_match        \
	-t $SCHEMA.artist_rel          \
	-t $SCHEMA.song                \
	-t $SCHEMA.lyrics              \
	-t $SCHEMA.performance         \
	-t $SCHEMA.record              \
	-t $SCHEMA.record_performance  \
	-t $SCHEMA.online_performance  \
	-t $SCHEMA.playlist            \
	-t $SCHEMA.playlist_detail     \
	-t $SCHEMA.chart               \
	-t $SCHEMA.chart_performance   \
| grep -v '^SET'  \
| grep -v '^\-\-'  \
| grep -v '^SELECT pg_catalog'  \
>> $OUTFILE

echo "PRAGMA foreign_keys=on;" >> $OUTFILE
echo "COMMIT;" >> $OUTFILE

echo build sqlite database
cat $OUTFILE | sqlite3 $SQLITEDB

